name: pytaxonkit
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - black>=22.6
 - pandas>=1.0
 - python>=3.6
 - pytest>=5.4
 - pytest-cov>=2.8
 - pytest-xdist>=1.31
 - taxonkit>=0.20.0
 - wget>=1.20
